[package]
name = "camera-monitor"
description = "LensGuard camera access monitoring daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
camera-core = { version = "0.4.0", path = "../crates/camera-core" }
camera-pipewire = { version = "0.4.0", path = "../crates/camera-pipewire" }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
